---
# tasks file for configure_git_and_command_prompt
- name: Download git-prompt.sh for root
  become: true
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    dest: /root/.git-prompt.sh

- name: Download git-prompt.sh for muthuks
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    dest: /home/muthuks/.git-prompt.sh

- name: Append source command for git-prompt.sh in .bashrc of root and muthuks
  become: true
  lineinfile:
    path: "{{ item }}"
    line: 'source ~/.git-prompt.sh'
    state: present
    backup: true
  loop:
    - "/root/.bashrc"
    - "/home/muthuks/.bashrc"

- name: Update PS1 variable in .bashrc for {{ mgmt_user }} user
  become: true
  lineinfile:
    path: "/home/{{ mgmt_user }}/.bashrc"
    line: "{{ ps1_variable_mgmt_user }}"
    state: present

- name: Update PS1 variable in .bashrc for root user
  become: true
  lineinfile:
    path: "/root/.bashrc"
    line: "{{ ps1_variable_root_user }}"
    state: present

########################### EOF #########################
