---
# tasks file for upgrade-server
- name: Upgrade the system packages
  become: true
  dnf:
    update_cache: true
    name: "*"
    state: latest

######################### EOF ######################### 
