apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-busybox
  template:
    metadata:
      labels:
        app: nginx-busybox
    spec:
      containers:
        - name: nginx-web-server
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
        - name: busybox-swiss-army-knife
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Hello from BusyBox!, I'm Running along Nginx!" > /usr/share/nginx/html/index.html;
              sleep 3600
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-busybox
spec:
  selector:
    app: nginx-busybox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 10.10.20.202
