#!/usr/bin/env ansible-playbook
- name: Playbook to build server.ms.local
  hosts: server
  roles:
    - name: Set Environment Vars for the Playbook
      role: setup_global_vars

    - name: Upgrade Packages
      role: upgrade-server

    - name: Install Required Packages
      role: install_required_packages

    - name: Generate SSH Keys
      role: generate_ssh_keys_of_server

    - name: Apply Firewall Rules
      role:  apply-firewall-rules

    - name: Configure httpd service ( Web Server)
      role: configure_httpd_service_of_server

    - name: Configure NFS service
      role: configure_nfs_service_of_server

    - name: Configure Chronyd ( NTP ) service
      role: configure_chronyd_service_of_server

    - name: Configure command prompt and git prompt
      role: configure_git_and_command_prompt

    - name: Setup PXE boot environment
      role: setup_pxe_boot_of_server

##################### EOF ##########################
