---
# tasks file for configure_httpd_service_of_server
- name: Create directory /var/www/{{ ansible_env.dnsbinder_server_fqdn }}
  become: true
  file:
    path: "/var/www/{{ ansible_env.dnsbinder_server_fqdn }}"
    state: directory
    owner: "{{ ansible_env.mgmt_super_user }}"
    group: "{{ ansible_env.mgmt_super_user }}"

- name: Create /var/www/{{ ansible_env.dnsbinder_server_fqdn }}/fancy-index
  file:
    path: "/var/www/{{ ansible_env.dnsbinder_server_fqdn }}/fancy-index"
    state: directory

- name: Copy fancy-index to /var/www/{{ ansible_env.dnsbinder_server_fqdn }}/fancy-index
  ansible.posix.synchronize:
    src: fancy-index/
    dest: "/var/www/{{ ansible_env.dnsbinder_server_fqdn }}/fancy-index/"

- name: Copy .htaccess file to /var/www/{{ ansible_env.dnsbinder_server_fqdn }}
  ansible.posix.synchronize:
    src: "/var/www/{{ ansible_env.dnsbinder_server_fqdn }}/fancy-index/.htaccess"
    dest: "/var/www/{{ ansible_env.dnsbinder_server_fqdn }}/.htaccess"

- name: Comment out Listen in default httpd.conf and ssl.conf files
  become: true
  replace:
    path: "{{ item }}"
    regexp: '^(Listen.*)'
    replace: '# \1'
    backup: true
  loop:
    - /etc/httpd/conf/httpd.conf
    - /etc/httpd/conf.d/ssl.conf

- name: Remove /etc/httpd/conf.d/welcome.conf if exists
  become: true
  file:
    path: /etc/httpd/conf.d/welcome.conf
    state: absent

- name: Generate private key
  become: true
  community.crypto.openssl_privatekey:
    path: "/etc/pki/tls/private/{{ ansible_env.dnsbinder_server_fqdn }}-apache-selfsigned.key"
    size: 2048
    type: RSA
    mode: '0600'

- name: Create certificate signing request (CSR) for self-signed certificate
  become: true
  community.crypto.openssl_csr_pipe:
    privatekey_path: "/etc/pki/tls/private/{{ ansible_env.dnsbinder_server_fqdn }}-apache-selfsigned.key"
    organization_name: "{{ ansible_env.dnsbinder_domain }}"
    common_name: "{{ ansible_env.dnsbinder_server_fqdn }}"  
    subject_alt_name:
      - "DNS:{{ ansible_env.dnsbinder_server_fqdn }}"
      - "DNS:{{ ansible_env.dnsbinder_server_short_name }}"
  register: ca_csr_content

- name: Generate self-signed certificate
  become: true
  community.crypto.x509_certificate:
    path: "/etc/pki/tls/certs/{{ ansible_env.dnsbinder_server_fqdn }}-apache-selfsigned.crt"
    privatekey_path: "/etc/pki/tls/private/{{ ansible_env.dnsbinder_server_fqdn }}-apache-selfsigned.key"
    csr_content: "{{ ca_csr_content.csr }}"
    provider: selfsigned
    selfsigned_not_after: +3650d  # valid for 10 years
    mode: '0644'

- name: Create custom httpd configuration for {{ ansible_env.dnsbinder_server_fqdn }}
  become: true
  template:
    src: custom_httpd_config.j2 
    dest: "/etc/httpd/conf.d/{{ ansible_env.dnsbinder_server_fqdn }}.conf"

- name: Copy self-signed SSL certificate to /etc/pki/ca-trust/source/anchors
  become: true
  ansible.posix.synchronize:
    src: "/etc/pki/tls/certs/{{ ansible_env.dnsbinder_server_fqdn }}-apache-selfsigned.crt"
    dest: "/etc/pki/ca-trust/source/anchors/{{ ansible_env.dnsbinder_server_fqdn }}-apache-selfsigned.crt"

- name: Run update-ca-trust
  become: true
  command: update-ca-trust
  changed_when: false

- name: Add NetworkManager-wait-online.service to as dependency for httpd.service
  become: true
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/httpd.service
    regexp: '^{{ item.key }}=(.*)$'
    line: '{{ item.key }}=\1 NetworkManager-wait-online.service'
    backrefs: true
  with_items:
    - { key: 'Wants' }
    - { key: 'After' }

- name: Enable and Start httpd service
  become: true
  systemd_service:
    name: httpd
    state: started
    enabled: true

- name: Restart httpd service
  become: true
  systemd_service:
    name: httpd
    state: restarted

############################# EOF ##############################
