run_ksmanager() {
    local hostname="$1"
    local ksmanager_options="$2"
    local cleanup_on_cancel="${3:-false}"  # Third parameter: whether to cleanup on cancel (default: false)
    local log_file

    # For --create-golden-image mode, hostname is not provided upfront
    if [[ "$ksmanager_options" == *"--create-golden-image"* ]]; then
        log_file="/tmp/ksmanager-golden-image-$$.log"
    else
        if [[ -z "$hostname" ]]; then
            print_error "run_ksmanager requires hostname"
            return 1
        fi
        log_file="/tmp/ksmanager-${hostname}-$$.log"
    fi

    # Create log file
    >"$log_file"

    # Execute ksmanager
    local ksmanager_exit_code=0
    if $lab_infra_server_mode_is_host; then
        if [[ -z "$hostname" ]]; then
            # For golden image creation without hostname
            ksmanager ${ksmanager_options} | tee -a "$log_file"
            ksmanager_exit_code=$?
        else
            ksmanager "${hostname}" ${ksmanager_options} | tee -a "$log_file"
            ksmanager_exit_code=$?
        fi
    else
        if [[ -z "$hostname" ]]; then
            # For golden image creation without hostname
            ssh -o LogLevel=QUIET -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t "${lab_infra_admin_username}@${lab_infra_server_hostname}" "ksmanager ${ksmanager_options}" | tee -a "$log_file"
            ksmanager_exit_code=$?
        else
            ssh -o LogLevel=QUIET -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t "${lab_infra_admin_username}@${lab_infra_server_hostname}" "ksmanager ${hostname} ${ksmanager_options}" | tee -a "$log_file"
            ksmanager_exit_code=$?
        fi
    fi

    # Check if user cancelled (exit code 130 or cancellation message in log)
    if [[ $ksmanager_exit_code -eq 130 ]] || grep -q "Operation cancelled by user" "$log_file"; then
        # Cleanup: remove DNS and MAC records only if this is a new install (not reimage)
        if [[ "$cleanup_on_cancel" == "true" ]] && [[ -n "$hostname" ]]; then
            print_info "Cleaning up resources for '${hostname}' due to cancellation..."
            if $lab_infra_server_mode_is_host; then
                ksmanager "${hostname}" --remove-host || true
            else
                ssh -o LogLevel=QUIET -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${lab_infra_admin_username}@${lab_infra_server_hostname}" "ksmanager ${hostname} --remove-host" || true
            fi
            print_info "Cleanup completed for '${hostname}' due to cancellation.\n"
        fi
        rm -f "$log_file"
        return 1
    fi

    # Check for other failures
    if [[ $ksmanager_exit_code -ne 0 ]]; then
        print_error "ksmanager execution failed."
        rm -f "$log_file"
        return 1
    fi

    # Extract values from log file (single pass: strip ANSI codes, parse all fields)
    # Note: MAC_ADDRESS is no longer extracted here - it's now generated by QEMU scripts and passed via --mac
    eval "$(awk -F': ' '
        { gsub(/\x1b\[[0-9;]*m/, "") }
        /IPv4 Address/ { ipv4 = $2; gsub(/[[:space:]]/, "", ipv4) }
        /IPv6 Address/ { ipv6 = $2; gsub(/[[:space:]]/, "", ipv6) }
        /OS distribution selected/ { os = $2; gsub(/\([^)]*\)/, "", os); gsub(/[[:space:]]/, "", os) }
        /Hostname/ { host = $2; gsub(/[[:space:]]/, "", host) }
        END {
            printf "IPV4_ADDRESS=%s\n", ipv4
            printf "IPV6_ADDRESS=%s\n", ipv6
            printf "OS_DISTRO=%s\n", os
            printf "EXTRACTED_HOSTNAME=%s\n", host
        }
    ' "$log_file")"

    # Clean up log file
    rm -f "$log_file"

    # MAC_ADDRESS validation removed - now managed by QEMU scripts

    # For golden image creation, we need hostname instead of IP
    if [[ "$ksmanager_options" == *"--create-golden-image"* ]]; then
        if [[ -z "${EXTRACTED_HOSTNAME}" ]]; then
            print_error "Failed to extract hostname from ksmanager output."
            print_info "Please check the lab infrastructure server VM at ${lab_infra_server_hostname} for details."
            return 1
        fi
    else
        # For regular VM operations, we need IP addresses
        if [[ -z "${IPV4_ADDRESS}" ]]; then
            print_error "Failed to extract IPv4 address from ksmanager output."
            print_info "Please check the lab infrastructure server VM at ${lab_infra_server_hostname} for details."
            return 1
        fi
        if [[ -z "${IPV6_ADDRESS}" ]]; then
            print_error "Failed to extract IPv6 address from ksmanager output."
            print_info "Please check the lab infrastructure server VM at ${lab_infra_server_hostname} for details."
            return 1
        fi
    fi

    # OS_DISTRO is optional - only validate if it was expected (golden-image mode)
    if [[ "$ksmanager_options" == *"--golden-image"* && -z "${OS_DISTRO}" ]]; then
        print_error "Failed to extract OS distro from ksmanager output."
        print_info "Please check the lab infrastructure server VM at ${lab_infra_server_hostname} for details."
        return 1
    fi

    return 0
}
