---
# tasks file for apply-firewall-rules
- name: Check if firewalld is active
  become: true
  command: systemctl is-active firewalld
  register: firewalld_status
  changed_when: false
  failed_when: false

- name: Notify if firewalld is not running
  debug:
    msg: |-
      Firewalld is not running. Skipping to add firewall rules.
  when: firewalld_status.stdout != "active"

- name: Notify if firewalld is running
  debug:
    msg: |-
      Firewalld is running. Proceeding to add firewall rules.
  when: firewalld_status.stdout == "active"

- name: Add local Network CIDR ( {{ ansible_env.dnsbinder_network_cidr }} ) to trusted zone
  become: true
  ansible.posix.firewalld:
    source: "{{ ansible_env.dnsbinder_network_cidr }}"
    zone: trusted
    permanent: true
    immediate: true
    state: enabled
  when: firewalld_status.stdout == "active"

#################### EOF #########################
