---
# tasks file for apply-firewall-rules
- name: Add local Network CIDR ( {{ ansible_env.dnsbinder_network_cidr }} ) to trusted zone
  become: true
  ansible.posix.firewalld:
    source: "{{ ansible_env.dnsbinder_network_cidr }}"
    zone: trusted
    permanent: true
    immediate: true
    state: enabled

#################### EOF #########################
