---
# tasks file for apply-firewall-rules
- name: Add server's local Network CIDR ( {{ server_mgmt_network }} ) to trusted zone
  become: true
  ansible.posix.firewalld:
    source: "{{ server_mgmt_network }}"
    zone: trusted
    permanent: true
    immediate: true
    state: enabled

#################### EOF #########################
